# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

pets=dict()
while True:
  x = input('Введите команду:')
  if x in 'добавить':
    name = input('Введите имя питомца: ')
    pets[name] = dict()
    types = 'Вид питомца: '
    types1 = input('Введите вид питомца: ')
    pets[name][types] = types1
    age = 'Возраст питомца: '
    age1 = int(input('Введите возраст питомца: '))
    a1 = ' года'
    a2 = ' год'
    a3 = ' лет'
    if (2<=age1%10<=4) and not (11<=age1%100<=14):
      pets[name][age] = str(age1)+a1
    elif age1%10==1 and age1%100!=11:
      pets[name][age] = str(age1)+a2
    else:
      pets[name][age] = str(age1)+a3
    names = 'Имя владельца: '
    names1 = input('Введите имя владельца: ')
    pets[name][names] = names1
  if x in 'вывести':
    print(pets)

