# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

x = dict()
z = int(input('от '))
q = int(input('до '))
for i in range(z, q+1):
  x[i] = i**i
print(x)

